name: 自动友链
on:
  issues:
    types: [opened, edited, closed]

jobs:
  add-friend-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 自动处理友链
        uses: coco5858/friend-link-action@main
        with:
          file_path: friends.json
          check_self: true
          self_link: https://com.z2m.store
          need_comment: true
      - name: 提交更新
        run: |
          git config --global user.name "FriendBot"
          git config --global user.email "bot@com.z2m.store"
          git add .
          git commit -m "🤖 自动添加友链"
          git push